apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-m0os
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0044-tenant/tkrw-pr712-0075-0044-app/devfile-sample-m0os@sha256:dceb1d741cda7709bbd81add308291e4885bedf23d6e07b0adfd931f0efacb96
        name: my-nodejs
        resources: {}
status: {}
